services:
  - type: web
    name: translation-proxy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: GEMINI_MODEL
        value: gemini-2.5-flash
      - key: CACHE_TTL_HOURS
        value: 72
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 60
      - key: ALLOWED_ORIGINS
        value: "*"
